INSERT INTO PHONES (QUANTITY, MODEL)
values (1, 'P1');
INSERT INTO PHONES (QUANTITY, MODEL)
values (1, 'P2');
INSERT INTO PHONES (QUANTITY, MODEL)
values (1, 'P3');
INSERT INTO PHONES (QUANTITY, MODEL)
values (1, 'P4');
INSERT INTO PHONES (QUANTITY, MODEL)
values (1, 'P5');
